version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    dns:
      - 8.8.8.8
    restart: unless-stopped